### ISSUE TITLE
`bulk-decaffeinate check` throws error

### ISSUE THREAD

**Issue by davej** [decaffeinate/bulk-decaffeinate#129]
```
> bulk-decaffeinate check
```

```
TypeError: Cannot read property 'split' of null
    at getTrackedFiles$ (/Users/dave/n/lib/node_modules/bulk-decaffeinate/dist/bulk-decaffeinate.js:977:19)
    at tryCatch (/Users/dave/n/lib/node_modules/bulk-decaffeinate/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/Users/dave/n/lib/node_modules/bulk-decaffeinate/node_modules/regenerator-runtime/runtime.js:303:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/dave/n/lib/node_modules/bulk-decaffeinate/node_modules/regenerator-runtime/runtime.js:117:21)
    at tryCatch (/Users/dave/n/lib/node_modules/bulk-decaffeinate/node_modules/regenerator-runtime/runtime.js:65:40)
    at invoke (/Users/dave/n/lib/node_modules/bulk-decaffeinate/node_modules/regenerator-runtime/runtime.js:155:20)
    at /Users/dave/n/lib/node_modules/bulk-decaffeinate/node_modules/regenerator-runtime/runtime.js:165:13
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)
```

Tried on Node.js 4, 6, 7 and 8, received the same error. MacOS 10.12.3.

**Comment by alangpierce** [comment]
Thanks for reporting! It looks like it's trying to run `git ls-files` and getting `null` as the output. Make sure you have git installed on your system and you're running bulk-decaffeinate from within a git repo.

If you're trying to run `bulk-decaffeinate check` outside of a git repo, let me know your use case and I can probably make it work. The file discovery approach ignores untracked files, which is why there's a git dependency even for `check`, but I could probably have it skip that step if it's not a git repo. You won't be able to run `convert`, though (without additional work), since a core part of `convert` is that it generates commits.

Regardless, the error should be better here.

**Comment by davej** [comment]
Ah cool. I was using it from within a git repo but I hadn't commited the coffee files to the repo yet. Ended up just using decaffeinate on its own and it worked fine. Thanks!
