### ISSUE TITLE
Cannot find module mz/fs

### ISSUE THREAD

**Issue by madskonradsen** [decaffeinate/bulk-decaffeinate#142]
I'm about to begin the transition of 1923 CoffeeScript files to TypeScript(yup, that's going to be fun) and already ran into a bug :D It _does_ sound like a decaffeinate bug, but seeing as it was run with bulk-decaffeinate I just suspect that it's something to do with bulk-decaffeinate. Has you experienced anything like that @alangpierce ? Have removed all globally installed packages and re-installed so it doesn't seem like stale modules.

from decaffeinate-errors.log
```
cof.coffee
module.js:557
    throw err;
    ^

Error: Cannot find module 'mz/fs'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/mads/.nvm/versions/node/v9.3.0/lib/node_modules/decaffeinate/dist/cli.js:5:12)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/mads/.nvm/versions/node/v9.3.0/lib/node_modules/decaffeinate/dist/index.js:25:13)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/mads/.nvm/versions/node/v9.3.0/lib/node_modules/decaffeinate/bin/decaffeinate:3:1)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:194:16)
    at bootstrap_node.js:618:3
```

**Comment by alangpierce** [comment]
Oops, I think this was a recent change. I just moved to the decaffeinate repo: https://github.com/decaffeinate/decaffeinate/issues/1251
